#!/bin/bash


# is used for case is filtering a list of files or text

Ls -l | grep ".txt"

#ls -l is used to list all files in the current dictory
#l directs the list generated by ls into the command
#grep ".txt" it will fiter the list to only show lines that have txt"

#Send output of one command to another
#Common mistakes: 
#Wrong order of the commands

#Troubleshooting:
#Test command separately at first	